### ISSUE TITLE
Blurry result

### ISSUE THREAD

**Issue by Albeforia** [Artiprocher/sd-webui-fastblend#3]
After processing the generated frames by FastBlend, all frames became blurry. Any ideas?

**Comment by Artiprocher** [comment]
Hi, @Albeforia . I have some suggestions.
* Upscale the frames using super-resolution methods, for example, ESRGAN.
* Use a smaller sliding window size.
Now my algorithm can remove flicker but sometimes make the frames blurry, because the inconsistent contents are blended together. I'm still working on improving this algorithm.

**Comment by Antonio-hi** [comment]
> Hi, [@Albeforia](https://github.com/Albeforia) . I have some suggestions.
> 
> * Upscale the frames using super-resolution methods, for example, ESRGAN.
> * Use a smaller sliding window size.
> 
> Now my algorithm can remove flicker but sometimes make the frames blurry, because the inconsistent contents are blended together. I'm still working on improving this algorithm.

This is worked for me, thanks
